/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserDashboard;

import java.awt.Color;

/**
 *
 * @author shu
 */
public class Userprofile extends javax.swing.JFrame {

    /**
     * Creates new form Userprofile
     */
    public Userprofile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        se = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        em = new javax.swing.JLabel();
        stat = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        full = new javax.swing.JLabel();
        cont = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        dashboardPanel = new javax.swing.JLabel();
        rs = new javax.swing.JLabel();
        r = new javax.swing.JLabel();
        se2 = new javax.swing.JLabel();
        se1 = new javax.swing.JLabel();
        cs = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        se.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        se.setText("Profile");
        se.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seMouseExited(evt);
            }
        });
        jPanel1.add(se, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 160, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Full Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("User Type:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Contact:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Status:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        em.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 140, 20));

        stat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 140, 20));

        type.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 140, 20));

        full.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(full, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, 20));

        cont.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 140, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 280, 330));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardPanel.setBackground(new java.awt.Color(0, 153, 204));
        dashboardPanel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        dashboardPanel.setText("DashBoard");
        dashboardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseExited(evt);
            }
        });
        jPanel3.add(dashboardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 40));

        rs.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rs.setText("My Reservations");
        rs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rsMouseExited(evt);
            }
        });
        jPanel3.add(rs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 140, 40));

        r.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        r.setText("Available Rooms");
        r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rMouseExited(evt);
            }
        });
        jPanel3.add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 140, 40));

        se2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        se2.setText("Settings");
        se2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                se2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                se2MouseExited(evt);
            }
        });
        jPanel3.add(se2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 110, 40));

        se1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        se1.setText("Profile");
        se1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                se1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                se1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                se1MouseExited(evt);
            }
        });
        jPanel3.add(se1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 70, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 40));

        cs.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        cs.setForeground(new java.awt.Color(10, 10, 10));
        cs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cs.setText("CozyStay");
        cs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                csMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                csMouseExited(evt);
            }
        });
        getContentPane().add(cs, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 160, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hotel LANDINGFORM.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seMouseClicked

    }//GEN-LAST:event_seMouseClicked

    private void seMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seMouseEntered
        se.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_seMouseEntered

    private void seMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seMouseExited
        se.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_seMouseExited

    private void dashboardPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseClicked
        UserDashboard ab = new UserDashboard ();
        ab.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardPanelMouseClicked

    private void dashboardPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseEntered
        dashboardPanel.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_dashboardPanelMouseEntered

    private void dashboardPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseExited
        dashboardPanel.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_dashboardPanelMouseExited

    private void rsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rsMouseEntered
        rs.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_rsMouseEntered

    private void rsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rsMouseExited
        rs.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_rsMouseExited

    private void rMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rMouseEntered
        r.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_rMouseEntered

    private void rMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rMouseExited
        r.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_rMouseExited

    private void se2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_se2MouseEntered
        se2.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_se2MouseEntered

    private void se2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_se2MouseExited
        se2.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_se2MouseExited

    private void se1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_se1MouseClicked
   
    }//GEN-LAST:event_se1MouseClicked

    private void se1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_se1MouseEntered
        se1.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_se1MouseEntered

    private void se1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_se1MouseExited
        se1.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_se1MouseExited

    private void csMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csMouseEntered
        cs.setForeground(new Color(0,255, 255));
    }//GEN-LAST:event_csMouseEntered

    private void csMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csMouseExited
        cs.setForeground(new Color(0 ,0, 0));
    }//GEN-LAST:event_csMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cont;
    private javax.swing.JLabel cs;
    private javax.swing.JLabel dashboardPanel;
    private javax.swing.JLabel em;
    private javax.swing.JLabel full;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel r;
    private javax.swing.JLabel rs;
    private javax.swing.JLabel se;
    private javax.swing.JLabel se1;
    private javax.swing.JLabel se2;
    private javax.swing.JLabel stat;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
