package UserDashboard;

import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER39
 */
public class UserDashboard extends javax.swing.JFrame {

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dashboardPanel = new javax.swing.JLabel();
        mr = new javax.swing.JLabel();
        se = new javax.swing.JLabel();
        cs = new javax.swing.JLabel();
        rs2 = new javax.swing.JLabel();
        se1 = new javax.swing.JLabel();
        ad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lo.setForeground(new java.awt.Color(255, 255, 255));
        lo.setText("Log out");
        lo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loMouseExited(evt);
            }
        });
        jPanel2.add(lo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 110, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled design (7).png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        dashboardPanel.setBackground(new java.awt.Color(0, 153, 204));
        dashboardPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dashboardPanel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardPanel.setText("DashBoard");
        dashboardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseExited(evt);
            }
        });
        jPanel2.add(dashboardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 30));

        mr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mr.setForeground(new java.awt.Color(255, 255, 255));
        mr.setText("My Reservation");
        mr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mrMouseExited(evt);
            }
        });
        jPanel2.add(mr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 30));

        se.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        se.setForeground(new java.awt.Color(255, 255, 255));
        se.setText("Profile");
        se.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seMouseExited(evt);
            }
        });
        jPanel2.add(se, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 30));

        cs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cs.setForeground(new java.awt.Color(255, 255, 255));
        cs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cs.setText("CozyStay");
        cs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                csMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                csMouseExited(evt);
            }
        });
        jPanel2.add(cs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 50));

        rs2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rs2.setForeground(new java.awt.Color(255, 255, 255));
        rs2.setText("Available Rooms");
        rs2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rs2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rs2MouseExited(evt);
            }
        });
        jPanel2.add(rs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 30));

        se1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        se1.setForeground(new java.awt.Color(255, 255, 255));
        se1.setText("Settings");
        se1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                se1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                se1MouseExited(evt);
            }
        });
        jPanel2.add(se1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 420));

        ad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ad.setText("User Dashboard");
        ad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adMouseExited(evt);
            }
        });
        getContentPane().add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 170, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hotel LANDINGFORM.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 590, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loMouseEntered
        lo.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_loMouseEntered

    private void loMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loMouseExited
        lo.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loMouseExited

    private void dashboardPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseClicked

    }//GEN-LAST:event_dashboardPanelMouseClicked

    private void dashboardPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseEntered
        dashboardPanel.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_dashboardPanelMouseEntered

    private void dashboardPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseExited
        dashboardPanel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_dashboardPanelMouseExited

    private void mrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mrMouseEntered
        mr.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_mrMouseEntered

    private void mrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mrMouseExited
        mr.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_mrMouseExited

    private void seMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seMouseEntered
        se.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_seMouseEntered

    private void seMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seMouseExited
        se.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_seMouseExited

    private void csMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csMouseEntered
        cs.setForeground(new Color(0,255, 255));
    }//GEN-LAST:event_csMouseEntered

    private void csMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csMouseExited
        cs.setForeground(new Color(255 ,255, 255));
    }//GEN-LAST:event_csMouseExited

    private void adMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adMouseEntered
        ad.setForeground(new Color(0,204, 204));
    }//GEN-LAST:event_adMouseEntered

    private void adMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adMouseExited
        ad.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_adMouseExited

    private void rs2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rs2MouseEntered
        rs2.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_rs2MouseEntered

    private void rs2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rs2MouseExited
       rs2.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_rs2MouseExited

    private void se1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_se1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_se1MouseEntered

    private void se1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_se1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_se1MouseExited

    private void seMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seMouseClicked
      Userprofile up = new Userprofile();
      up.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_seMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad;
    private javax.swing.JLabel cs;
    private javax.swing.JLabel dashboardPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lo;
    private javax.swing.JLabel mr;
    private javax.swing.JLabel rs2;
    private javax.swing.JLabel se;
    private javax.swing.JLabel se1;
    // End of variables declaration//GEN-END:variables
}
