/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;

/**
 *
 * @author shu
 */
public class AboutUs extends javax.swing.JFrame {

    /**
     * Creates new form AboutUs
     */
    public AboutUs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        bn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        hm = new javax.swing.JLabel();
        rm = new javax.swing.JLabel();
        ab = new javax.swing.JLabel();
        cn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 153, 51));

        bn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bn.setText("Book Now");
        bn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bnMouseExited(evt);
            }
        });
        jPanel4.add(bn);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 70, 20));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        hm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hm.setText("Home");
        hm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hmMouseExited(evt);
            }
        });
        jPanel1.add(hm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, 20));

        rm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rm.setText("Rooms");
        rm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rmMouseExited(evt);
            }
        });
        jPanel1.add(rm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 20));

        ab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ab.setText("About Us");
        ab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                abMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                abMouseExited(evt);
            }
        });
        jPanel1.add(ab, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 90, 20));

        cn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cn.setText("Contact");
        cn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cnMouseExited(evt);
            }
        });
        jPanel1.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 80, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setText("About Us");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 150, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Welcome to Cozy Stay, your home away from home. We offer a warm, comfortable space ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("where you can relax, recharge, and make lasting memories. From our soft beds to our ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 550, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("friendly service, every detail is designed to make your stay effortless and enjoyable.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Experience comfort, tranquility, and a personal touch that makes Cozy Stay truly special.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Your paragraph text (4).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnMouseClicked
        Registerform rf = new Registerform ();
        rf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bnMouseClicked

    private void bnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnMouseEntered
        bn.setForeground(new Color(255,239,0));
    }//GEN-LAST:event_bnMouseEntered

    private void bnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnMouseExited
        bn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_bnMouseExited

    private void hmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hmMouseClicked
        Landingform lf = new Landingform ();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hmMouseClicked

    private void hmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hmMouseEntered
        hm.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_hmMouseEntered

    private void hmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hmMouseExited
        hm.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_hmMouseExited

    private void rmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rmMouseClicked
        Room rm = new Room ();
        rm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rmMouseClicked

    private void rmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rmMouseEntered
        rm.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_rmMouseEntered

    private void rmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rmMouseExited
        rm.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_rmMouseExited

    private void abMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abMouseClicked
        AboutUs ab = new AboutUs ();
        ab.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_abMouseClicked

    private void abMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abMouseEntered
        ab.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_abMouseEntered

    private void abMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abMouseExited
        ab.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_abMouseExited

    private void cnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnMouseClicked
        Contact cn = new Contact ();
        cn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cnMouseClicked

    private void cnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnMouseEntered
        cn.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_cnMouseEntered

    private void cnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnMouseExited
        cn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_cnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ab;
    private javax.swing.JLabel bn;
    private javax.swing.JLabel cn;
    private javax.swing.JLabel hm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel rm;
    // End of variables declaration//GEN-END:variables
}
