package Forms;


import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shu
 */
public class Landingform extends javax.swing.JFrame {

    /**
     * Creates new form Landingform
     */
    public Landingform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cs = new javax.swing.JLabel();
        tx = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Continue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cs.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        cs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cs.setText("CozyStay");
        cs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                csMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                csMouseExited(evt);
            }
        });
        jPanel2.add(cs, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        tx.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx.setText("A comfy place to relax and feel at home.");
        tx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txMouseExited(evt);
            }
        });
        jPanel2.add(tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ⓒ @ CozyStay 2026");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, 20));

        Continue.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Continue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Continue.setText("Click here as Guest!");
        Continue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContinueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContinueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContinueMouseExited(evt);
            }
        });
        jPanel2.add(Continue, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hotel LANDINGFORM.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 420));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ContinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueMouseClicked
        Loginform lg = new Loginform ();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ContinueMouseClicked

    private void ContinueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueMouseEntered
       Continue.setForeground(new Color(245, 185, 105));
    }//GEN-LAST:event_ContinueMouseEntered

    private void ContinueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinueMouseExited
        Continue.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_ContinueMouseExited

    private void csMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csMouseEntered
         cs.setForeground(new Color(255, 200, 100));
    }//GEN-LAST:event_csMouseEntered

    private void csMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csMouseExited
         cs.setForeground(new Color(0, 0, 0)); 
    }//GEN-LAST:event_csMouseExited

    private void txMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txMouseEntered
        tx.setForeground(new Color(255, 200, 100));
    }//GEN-LAST:event_txMouseEntered

    private void txMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txMouseExited
       tx.setForeground(new Color(0, 0, 0)); 
    }//GEN-LAST:event_txMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Landingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Landingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Landingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Landingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Landingform().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Continue;
    private javax.swing.JLabel cs;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tx;
    // End of variables declaration//GEN-END:variables
}
