package Forms;


import Config.Session;
import Config.config;
import Dashboard.Admindashboard;
import UserDashboard.UserDashboard;
import config.passUtil;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shu
 */
public class Loginform extends javax.swing.JFrame {

    /**
     * Creates new form Loginform
     */
    public Loginform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lo = new javax.swing.JPanel();
        l = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        si = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        b = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Create an Account?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setText("Welcome Back!");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 200, 30));

        lo.setBackground(new java.awt.Color(99, 95, 95));
        lo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loMouseEntered(evt);
            }
        });

        l.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        l.setText("Login");
        l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lMouseExited(evt);
            }
        });
        lo.add(l);

        getContentPane().add(lo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 90, 40));

        jLabel8.setText("Please login to your account!");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        si.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        si.setForeground(new java.awt.Color(0, 102, 255));
        si.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        si.setText("Sign In");
        si.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                siMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                siMouseExited(evt);
            }
        });
        getContentPane().add(si, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, 30));

        jPanel1.setBackground(new java.awt.Color(99, 95, 95));

        b.setBackground(new java.awt.Color(0, 0, 0));
        b.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b.setText("Back");
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bMouseExited(evt);
            }
        });
        jPanel1.add(b);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 60, 40));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Email:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 50, 50));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 160, 30));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Password:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/FINAL.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, -10, 120, 130));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LOGINFORM.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 330, 420));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/roam.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void siMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siMouseClicked
      Registerform rf = new Registerform();
      rf.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_siMouseClicked

    private void siMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siMouseEntered
      si.setForeground(new Color(0, 255, 255, 200));
    }//GEN-LAST:event_siMouseEntered

    private void siMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siMouseExited
      si.setForeground(new Color(0, 0, 0)); 
    }//GEN-LAST:event_siMouseExited

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void loMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loMouseClicked

    }//GEN-LAST:event_loMouseClicked

    private void bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseClicked
     Landingform lf = new Landingform();
      lf.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_bMouseClicked

    private void bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseEntered
      b.setForeground(new Color(255, 153, 153));
    }//GEN-LAST:event_bMouseEntered

    private void bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseExited
    b.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_bMouseExited

    private void lMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMouseEntered
    l.setForeground(new Color(255, 153, 153));
    }//GEN-LAST:event_lMouseEntered

    private void lMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMouseExited
    l.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_lMouseExited

    private void loMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loMouseEntered
    
    }//GEN-LAST:event_loMouseEntered

    private void lMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMouseClicked
    String Email = email.getText().trim();
String pass = passUtil.hashPassword(new String(password.getPassword()));

if (Email.isEmpty() || pass.isEmpty()) {
    JOptionPane.showMessageDialog(
        this,
        "Type your User and Password.",
        "Missing Information",
        JOptionPane.WARNING_MESSAGE
    );
    return;
}

config con = new config();
String sql = "SELECT * FROM account WHERE email = ? AND password = ? AND status = ?";

String account_Type = con.authenticate(
        sql,
        Email,
        pass,
        "Active"   // ✅ Only allows login if status is Active
);

if (account_Type != null) {

    try {
        // Get full user row
        ResultSet rs = con.getData("SELECT * FROM account WHERE email = '" + Email + "'");

        if (rs.next()) {

            // Set Session
            Session.setSession(
                    rs.getString("email"),
                    rs.getString("fullname"),
                    rs.getString("contact"),
                    rs.getString("type"),
                    rs.getString("status")
            );
        }

    } catch (SQLException ex) {
        System.out.println("Login Error: " + ex.getMessage());
    }

    JOptionPane.showMessageDialog(null, "Log in successful");

    // ✅ Redirect to proper dashboard
    if (account_Type.equals("Admin")) {
        new Admindashboard().setVisible(true);
        this.dispose();
    } 
    else if (account_Type.equals("User")) {
        new UserDashboard().setVisible(true);
        this.dispose();
    }

} 
else {

    // 🔎 Check if account exists but not Active
    try {
        ResultSet checkAccount = con.getData(
                "SELECT * FROM account WHERE email = '" + Email + "' AND password = '" + pass + "'"
        );

        if (checkAccount.next()) {

            String status = checkAccount.getString("status");

            if (!status.equalsIgnoreCase("Active")) {

                JOptionPane.showMessageDialog(
                        this,
                        "Wait for admin to activate your status.",
                        "Account Not Activated",
                        JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }
        }

    } catch (SQLException ex) {
        System.out.println("Status Check Error: " + ex.getMessage());
    }

    // ❌ If email/password is wrong
    JOptionPane.showMessageDialog(
            this,
            "Invalid Email or Password.",
            "Login Failed",
            JOptionPane.ERROR_MESSAGE
    );
}
       
    }//GEN-LAST:event_lMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l;
    private javax.swing.JPanel lo;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel si;
    // End of variables declaration//GEN-END:variables
}
