/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;

/**
 *
 * @author shu
 */
public class Room extends javax.swing.JFrame {

    /**
     * Creates new form Room
     */
    public Room() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bn = new javax.swing.JLabel();
        hm = new javax.swing.JLabel();
        rm = new javax.swing.JLabel();
        ab = new javax.swing.JLabel();
        cn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 153, 51));

        bn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bn.setText("Book Now");
        bn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bnMouseExited(evt);
            }
        });
        jPanel4.add(bn);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 70, 20));

        hm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        hm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hm.setText("Home");
        hm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hmMouseExited(evt);
            }
        });
        jPanel1.add(hm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, 20));

        rm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rm.setText("Rooms");
        rm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rmMouseExited(evt);
            }
        });
        jPanel1.add(rm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 20));

        ab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ab.setText("About Us");
        ab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                abMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                abMouseExited(evt);
            }
        });
        jPanel1.add(ab, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 90, 20));

        cn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cn.setText("Contact");
        cn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cnMouseExited(evt);
            }
        });
        jPanel1.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 80, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled design (11).png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Deluxe Room");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled design (12).png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Executive Room");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("* A room for a perfect couples");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("* Double Bed");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("* Free Wi-Fi");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("* Breakfast Included");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("* A special suite with good bed");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("* King size bed.");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("* Living Area.");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("* Ocean View Balcony");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 490, 220));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 720, 180));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hotel LANDINGFORM.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnMouseClicked
        Registerform rf = new Registerform ();
        rf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bnMouseClicked

    private void bnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnMouseEntered
        bn.setForeground(new Color(255,239,0));
    }//GEN-LAST:event_bnMouseEntered

    private void bnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnMouseExited
        bn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_bnMouseExited

    private void hmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hmMouseClicked
        Landingform lf = new Landingform ();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hmMouseClicked

    private void hmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hmMouseEntered
        hm.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_hmMouseEntered

    private void hmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hmMouseExited
        hm.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_hmMouseExited

    private void rmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rmMouseClicked
        Room rm = new Room ();
        rm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rmMouseClicked

    private void rmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rmMouseEntered
        rm.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_rmMouseEntered

    private void rmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rmMouseExited
        rm.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_rmMouseExited

    private void abMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abMouseClicked
        AboutUs ab = new AboutUs ();
        ab.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_abMouseClicked

    private void abMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abMouseEntered
        ab.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_abMouseEntered

    private void abMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abMouseExited
        ab.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_abMouseExited

    private void cnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnMouseClicked
        Contact cn = new Contact ();
        cn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cnMouseClicked

    private void cnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnMouseEntered
        cn.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_cnMouseEntered

    private void cnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnMouseExited
        cn.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_cnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ab;
    private javax.swing.JLabel bn;
    private javax.swing.JLabel cn;
    private javax.swing.JLabel hm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel rm;
    // End of variables declaration//GEN-END:variables
}
