/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminDashboard;

import Config.config;
import Dashboard.Admindashboard;
import Forms.Loginform;
import Forms.userForm;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.TableModel;

/**
 *
 * @author shu
 */
public class Userpanel extends javax.swing.JFrame {

    /**
     * Creates new form Userpanel
     */
    public Userpanel() {
        initComponents();
        getUserData();
    }
    void getUserData() {
        config con = new config();
        String sql = "Select * FROM account ";
       con.displayData(sql, userTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dashboardPanel = new javax.swing.JLabel();
        rs = new javax.swing.JLabel();
        r = new javax.swing.JLabel();
        us = new javax.swing.JLabel();
        re = new javax.swing.JLabel();
        se = new javax.swing.JLabel();
        cs = new javax.swing.JLabel();
        se1 = new javax.swing.JLabel();
        ad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        update = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        search_btn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        refresh = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lo.setForeground(new java.awt.Color(255, 255, 255));
        lo.setText("Log out");
        lo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loMouseExited(evt);
            }
        });
        jPanel2.add(lo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 110, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled design (7).png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        dashboardPanel.setBackground(new java.awt.Color(0, 153, 204));
        dashboardPanel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        dashboardPanel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardPanel.setText("DashBoard");
        dashboardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseExited(evt);
            }
        });
        jPanel2.add(dashboardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 30));

        rs.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rs.setForeground(new java.awt.Color(255, 255, 255));
        rs.setText("Reservations");
        rs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rsMouseExited(evt);
            }
        });
        jPanel2.add(rs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 30));

        r.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        r.setForeground(new java.awt.Color(255, 255, 255));
        r.setText("Rooms");
        r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rMouseExited(evt);
            }
        });
        jPanel2.add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 30));

        us.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        us.setForeground(new java.awt.Color(255, 255, 255));
        us.setText("Users");
        us.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usMouseExited(evt);
            }
        });
        jPanel2.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 30));

        re.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        re.setForeground(new java.awt.Color(255, 255, 255));
        re.setText("Reports");
        re.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reMouseExited(evt);
            }
        });
        jPanel2.add(re, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 30));

        se.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        se.setForeground(new java.awt.Color(255, 255, 255));
        se.setText("Settings");
        se.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seMouseExited(evt);
            }
        });
        jPanel2.add(se, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 110, 30));

        cs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cs.setForeground(new java.awt.Color(255, 255, 255));
        cs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cs.setText("CozyStay");
        cs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                csMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                csMouseExited(evt);
            }
        });
        jPanel2.add(cs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 50));

        se1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        se1.setForeground(new java.awt.Color(255, 255, 255));
        se1.setText("Profile");
        se1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                se1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                se1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                se1MouseExited(evt);
            }
        });
        jPanel2.add(se1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 420));

        ad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ad.setText("Admin Dashboard");
        ad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adMouseExited(evt);
            }
        });
        getContentPane().add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 170, 40));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(userTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 530, 330));

        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Update");
        update.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 5, -1, -1));

        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 70, 27));

        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 20));

        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 70, 27));

        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Delete");
        delete.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 70, -1));

        search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        search.setOpaque(false);
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 130, 27));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Search");
        search_btn.add(jLabel7);

        getContentPane().add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 60, 27));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Refresh");
        refresh.add(jLabel6);

        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 60, 27));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled design (7).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void csMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csMouseEntered
        cs.setForeground(new Color(0,255, 255));
    }//GEN-LAST:event_csMouseEntered

    private void csMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csMouseExited
        cs.setForeground(new Color(255 ,255, 255));
    }//GEN-LAST:event_csMouseExited

    private void loMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loMouseEntered
        lo.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_loMouseEntered

    private void loMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loMouseExited
        lo.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_loMouseExited

    private void dashboardPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseClicked
    Admindashboard ad = new Admindashboard ();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardPanelMouseClicked

    private void dashboardPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseEntered
        dashboardPanel.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_dashboardPanelMouseEntered

    private void dashboardPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseExited
        dashboardPanel.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_dashboardPanelMouseExited

    private void rsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rsMouseEntered
        rs.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_rsMouseEntered

    private void rsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rsMouseExited
        rs.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_rsMouseExited

    private void rMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rMouseEntered
        r.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_rMouseEntered

    private void rMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rMouseExited
        r.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_rMouseExited

    private void usMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usMouseEntered
        us.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_usMouseEntered

    private void usMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usMouseExited
        us.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_usMouseExited

    private void reMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reMouseEntered
        re.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_reMouseEntered

    private void reMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reMouseExited
        re.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_reMouseExited

    private void seMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seMouseEntered
        se.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_seMouseEntered

    private void seMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seMouseExited
        se.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_seMouseExited

    private void adMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adMouseEntered
        ad.setForeground(new Color(0,204, 204));
    }//GEN-LAST:event_adMouseEntered

    private void adMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adMouseExited
        ad.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_adMouseExited

    private void se1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_se1MouseClicked
        Profilepanel pl = new Profilepanel();
        pl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_se1MouseClicked

    private void se1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_se1MouseEntered
        se1.setForeground(new Color(0,153,153));
    }//GEN-LAST:event_se1MouseEntered

    private void se1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_se1MouseExited
        se1.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_se1MouseExited

    private void usMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usMouseClicked
     Userpanel up = new Userpanel ();
        up.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_usMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked

       userForm stf = new userForm();
       stf.setVisible(true);
       this.dispose();
       stf.action = "Add";
       stf.st_label.setText("SAVE");
    }//GEN-LAST:event_addMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
                int rowIndex = userTable.getSelectedRow();
          if(rowIndex < 0){
              JOptionPane.showMessageDialog(null, "Please Select an Item!");
          } else {
              TableModel model = userTable.getModel();
              userForm stf = new userForm(); 

              
              stf.userid.setText(String.valueOf(model.getValueAt(rowIndex, 0)));
              stf.email.setText(String.valueOf(model.getValueAt(rowIndex, 1)));
              stf.full.setText(String.valueOf(model.getValueAt(rowIndex, 2)));
              stf.pass.setText(String.valueOf(model.getValueAt(rowIndex, 3)));
              stf.cont.setText(String.valueOf(model.getValueAt(rowIndex, 4)));

              stf.action = "Update";
              stf.st_label.setText("UPDATE");

              stf.pack();
              stf.setLocationRelativeTo(null);
              stf.setVisible(true);

              
              java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
              if (win != null) {
                  win.dispose();
              }
          }
    }//GEN-LAST:event_updateMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
         int rowIndex = userTable.getSelectedRow();
        if(rowIndex < 0){
            JOptionPane.showMessageDialog(null, "Please select data first from the table!");
        }else{
            TableModel model = userTable.getModel();
            Object value = model.getValueAt(rowIndex, 0);
            String id = value.toString();
            int a = JOptionPane.showConfirmDialog(null, "Are you sure to delete ID: "+id);
            if(a == JOptionPane.YES_OPTION){
                config con = new config();
                int u_id = Integer.parseInt(id);
                con.deleteData(u_id, "tbl_users", "u_id");
                getUserData();
            }
        }
    }//GEN-LAST:event_deleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userpanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad;
    private javax.swing.JPanel add;
    private javax.swing.JLabel cs;
    private javax.swing.JLabel dashboardPanel;
    private javax.swing.JPanel delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lo;
    private javax.swing.JLabel r;
    private javax.swing.JLabel re;
    private javax.swing.JPanel refresh;
    private javax.swing.JLabel rs;
    private javax.swing.JLabel se;
    private javax.swing.JLabel se1;
    private javax.swing.JTextField search;
    private javax.swing.JPanel search_btn;
    private javax.swing.JPanel update;
    private javax.swing.JLabel us;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
